# Generated by Django 5.0.3 on 2024-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_urltable_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltable',
            name='short_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
